### ISSUE TITLE
Links text has redundant quotes

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#145]
I've noticed that some of the link text has redundant quotes at the end.
For instance topic https://en.wikipedia.org/wiki/Anarchism has a link in 2nd section `archon` which doesn't have quotes at the end but parser returns with a quotes.
 
<img width="679" alt="2018-08-15_1516" src="https://user-images.githubusercontent.com/435827/44147974-0a0e7070-a09f-11e8-8286-6bba6c88ac51.png">

<img width="946" alt="2018-08-15_1517" src="https://user-images.githubusercontent.com/435827/44148186-dfbc1e48-a09f-11e8-9bb4-63418d046579.png">

**Comment by spencermountain** [comment]
ahh, good eye!
will fix this pronto.
thanks

**Comment by spencermountain** [comment]
fixed in 5.1.0
thanks!

**Comment by yanosh-igor** [comment]
Hi @spencermountain,
Looks like issue still exists.
https://en.wikipedia.org/wiki/Hud

![2018-12-11_1351](https://user-images.githubusercontent.com/435827/49798829-f20b4700-fd4b-11e8-8370-594e0464b949.png)

**Comment by spencermountain** [comment]
thanks
