### ISSUE TITLE
Parsing issues with Cyrillic pages

### ISSUE THREAD

**Issue by ramusus** [spencermountain/wtf_wikipedia#251]
```
wtf.fetch('Горбатая_гора', 'ru', function(err, doc) {
  console.log(doc)
});
```

For example, [this page](https://ru.wikipedia.org/wiki/Горбатая_гора) is not parsed well keeping all sentences in place, because of [this line](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/03-paragraph/index.js#L5). Regular expression contains `\W*` and Cyrillic symbols assumed as non-word character as mentioned [here](https://stackoverflow.com/a/18471465/87535) (who knows why..).

Changing this line to 

```const twoNewLines = /\r?\n\r?\n/;```

should solve the issue.

**Comment by spencermountain** [comment]
oh hey! good find.
thanks for this. fixed in `7.2.10`
lemme know if you see anything else.

**Comment by ramusus** [comment]
The problem still here because method `parseParagraphs` still works incorrectly.

**Comment by ramusus** [comment]
It removes a big part of the text from the source, using regular expressions, that works in the wrong way with Cyrillic symbols.

**Comment by spencermountain** [comment]
ah, ok. thank you.

**Comment by ramusus** [comment]
@spencermountain Is there anything prevents from fixing regular expression?

**Comment by spencermountain** [comment]
nope, prs welcome
