### ISSUE TITLE
Fetching an array does not return array if there's just one item

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#418]
This works because docList is an array:

```
wtf
  .fetch(['Royal Cinema', 'Aldous Huxley'], 'en', {
    'Api-User-Agent': 'user@example.com',
  })
  .then((docList) => {
    let links = docList.map((doc) => doc.links())
    console.log(links)
  })
```

But if there happens to be just 1 item to fetch, docList is not an array and crashes.

```
wtf
  .fetch(['Royal Cinema'], 'en', {
    'Api-User-Agent': 'user@example.com',
  })
  .then((docList) => {
    let links = docList.map((doc) => doc.links())
    console.log(links)
  })
```

Wouldn't it be better if docList was always an array, even if only with 1 item?

NB Our workaround we found is as follows, but it's ugly:

```
wtf
  .fetch(['Royal Cinema'], 'en', {
    'Api-User-Agent': 'user@example.com',
  })
  .then((docList) => {
    if (typeof docList[0] === 'undefined') {
      docList = [docList]
    }
    let links = docList.map((doc) => doc.links())
    console.log(links)
  })
```

**Comment by Vacilando** [comment]
I see this is solved on dev - will it be coming to the main branch?

**Comment by spencermountain** [comment]
hey sorry Tomáš - yeah, I believe this is fixed in v9.
Please let me know if you continue to see an issue - i'm happy to fix this for ya
cheers

**Comment by Vacilando** [comment]
@wvanderp and @spencermountain, thanks for your fix, I see it in the current prod version.

However, I am still seeing docList coming in as an object in https://github.com/Vacilando/gatsby-wikipedia-fetcher/blob/main/gatsby-node.js#L152, meaning docList[0] is undefined and I have to make an array out of it.
But it's possible that it's my code that is faulty there in some way.

**Comment by wvanderp** [comment]
fetch has a few "modes", depending on what you provide it with.

If you supply it with a single pageID or title, it will return a Document object.
If you supply a wiki URL, we will parse it and use the tile and provide a single Document object
if you supply it with an array with pageIDs or an array of titles, it will return an array of document objects.

There is another catch in the programming you need if you provide an array; it needs to be eighter pageIDs or titles they can not be mixed.

if you provide an array with a singular title or pageID in it, it should return an array with a document in it
