### ISSUE TITLE
Getting all data from infobox

### ISSUE THREAD

**Issue by rbbt99** [spencermountain/wtf_wikipedia#562]
I'm using this page for example: https://en.wikipedia.org/wiki/Tony_Hawk%27s_Pro_Skater

I'm interested in the following data:
![obraz](https://github.com/spencermountain/wtf_wikipedia/assets/147496715/00bb4312-4b56-4561-a752-f470b33942cb)

But the wtf_wikipedia only returns platform names without the dates. How can I extract all data including dates?

**Comment by spencermountain** [comment]
oh hey, that's a good catch - looks like {{vgrelease}} is a alias for [Template:Video_game_release](https://en.m.wikipedia.org/wiki/Template:Video_game_release).
Fixed on dev, will be part of the next release.
For the mean-time, you can do something like:
```js
wtf.extend((models, templates) => {
  templates.vgrelease = ['region', 'date', 'region2', 'date2', 'region3', 'date3', 'region4', 'date4']
})
```
cheers

**Comment by rbbt99** [comment]
Thank you for your quick response! Unfortunately I still don't get the dates, the code I'm using:

`import wtf from './src/index.js'
console.log('start')

wtf.extend((models, templates) => {
  templates.vgrelease = ['region', 'date', 'region2', 'date2', 'region3', 'date3', 'region4', 'date4']
})

const doc = await wtf.fetch('https://en.wikipedia.org/wiki/Tony_Hawk%27s_Pro_Skater')

console.log(doc.infoboxes())`

**Comment by spencermountain** [comment]
oh, right
https://runkit.com/spencermountain/652d6ccdaeee710008287a5b
this should do it. Otherwise, new release with the fix in a couple days.
cheers

**Comment by rbbt99** [comment]
Thank you very much!
